[package]
name = "tmp117"
version = "0.1.0"
edition = "2021"
authors = ["xgroleau <xavgroleau@gmail.com>"]

[lib]
harness = false

[dependencies]
defmt = { version = "0.3.0", optional = true}
# panic-probe = { version = "0.3.0", features = ["print-defmt"], optional = true}

embedded-hal = { version = "1.0.0-alpha.7" }
embedded-hal-async = { version = "0.1.0-alpha.1" }

bit = "0.1.1"
modular-bitfield = "0.11.2"
device-register = { version = "0.1.0", git = "https://github.com/xgroleau/device-register" }
device-register-async = { version = "0.1.0", git = "https://github.com/xgroleau/device-register" }

# [dev-dependencies]
# cortex-m = "0.7.3"
# cortex-m-rt = "0.7.1"

# embassy-executor = { version = "0.1.0",  features = ["defmt", "nightly", "unstable-traits"] }
# embassy-nrf = { version = "0.1.0", features = ["defmt", "nrf52840", "time-driver-rtc1", "gpiote", "nightly", "unstable-traits"] }

# defmt = "0.3.0"
# defmt-rtt = "0.3.0"
# defmt-test = "0.3.0"
# v3_2 = { version = "0.1.0", path = "../../bsp/boards/v3_2" }
