# Before upgrading check that everything is available on all tier1 targets here:
# https://rust-lang.github.io/rustup-components-history
# x86 is to build the doc and clippy
[toolchain]
channel = "nightly-2022-06-28"
components = [ "clippy", "llvm-tools-preview", "rustfmt" ]
targets = [ "x86_64-unknown-linux-gnu" ]
