# Before upgrading check that everything is available on all tier1 targets here:
# https://rust-lang.github.io/rustup-components-history
[toolchain]
channel = "nightly-2022-03-10"
components = [ "clippy", "rustfmt" ]
targets = [ "thumbv7em-none-eabihf"]
authors = ["xgroleau <xavgroleau@gmail.com>"]

[lib]
harness = false

[features]
default = [ "defmt" ]

[dependencies]
defmt = { version = "0.3.0", optional = true}

embedded-hal = { version = "1.0.0-alpha.7" }
embedded-hal-async = { version = "0.1.0-alpha.1" }

register-macros = { path = "./register-macros", version = "0.1.0" }
bit = "0.1.1"
modular-bitfield = "0.11.2"

# [dev-dependencies]
# cortex-m = "0.7.3"
# cortex-m-rt = "0.7.1"

# embassy-executor = { version = "0.1.0",  features = ["defmt", "nightly", "unstable-traits"] }
# embassy-nrf = { version = "0.1.0", features = ["defmt", "nrf52840", "time-driver-rtc1", "gpiote", "nightly", "unstable-traits"] }

# defmt = "0.3.0"
# defmt-rtt = "0.3.0"
# defmt-test = "0.3.0"
# v3_2 = { version = "0.1.0", path = "../../bsp/boards/v3_2" }
